version: "3.8"
services:
  app:
    image: gitlab:01
    container_name: gitlab
    build: 
      context: .
      network: host
      dockerfile: Dockerfile
      args:
        - DEV_gitlab=1
    ipc: host
    hostname: 'gitlab.example.com'
    environment:
    #- AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
    #- AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    - HOME=/app
    - DATA=/app/data
    ports:
      - "8888:8888"
      - "80:80"
      - "443:443"
      - "22:22"
    volumes:
      - .:/app
      - $HOME/data/gitlabdata:/app/data
      - $HOME/data/gitlabdata/config:/etc/gitlab
      - $HOME/data/gitlabdata/logs:/var/log/gitlab
      - $HOME/data/gitlabdata/data:/var/opt/gitlab
    shm_size: '256m'
